name:         mantler
version:      "0.0.0.0"
synopsis:     Reconstructing heavy resonances in the antler decay topology using the singularity variable
author:       Chan Beom Park
maintainer:   cbpark@gmail.com
license-file: LICENSE
github:       cbpark/mantler
category:     Physics

ghc-options:  -Wall -Wcompat -O2 -funbox-strict-fields

dependencies:
  - base >= 4.12.0.0 && < 5
  - hmatrix-gsl
  - hep-utilities

library:
  exposed-modules: HEP.Kinematics.Antler
  source-dirs: lib
