name:         Mantler
version:      "0.0.0.0"
# synopsis:
author:       Chan Beom Park
maintainer:   cbpark@gmail.com
license-file: LICENSE
github:       cbpark/Mantler
category:     Physics

ghc-options:  -Wall -O2 -funbox-strict-fields

dependencies:
  - base >= 4.12.0.0 && < 5
  - bytestring
  - pipes
  - pipes-bytestring
  - zlib
  - hep-utilities

executables:
  sigmaATLHEF:
    main: sigmaATLHEF.hs
    source-dirs: src
