name:         mantler
version:      "0.0.0.0"
# synopsis:
author:       Chan Beom Park
maintainer:   cbpark@gmail.com
license-file: LICENSE
github:       cbpark/mantler
category:     Physics

ghc-options:  -Wall -Wcompat -O2 -funbox-strict-fields

dependencies:
  - base >= 4.12.0.0 && < 5
  - hep-utilities

library:
  exposed-modules:
    - HEP.Kinematics.Antler
  source-dirs: lib
  dependencies: hmatrix-gsl

executables:
  phasespace1:
    main: phasespace1.hs
    source-dirs: src
    dependencies:
      - bytestring
      - double-conversion
      - pipes
      - pipes-bytestring
      - zlib
      - mantler

  phasespace2:
    main: phasespace2.hs
    source-dirs: src
    dependencies:
      - bytestring
      - double-conversion
      - pipes
      - pipes-bytestring
      - zlib
      - mantler

  atLHEF1:
    main: atLHEF1.hs
    source-dirs: src
    dependencies:
      - bytestring
      - double-conversion
      - pipes
      - pipes-bytestring
      - zlib
      - mantler

  atLHEF2:
    main: atLHEF2.hs
    source-dirs: src
    dependencies:
      - bytestring
      - double-conversion
      - pipes
      - pipes-bytestring
      - zlib
      - mantler
